language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: BRZFHZHxY8fEu6Zv0wM+LpZNuocqIjINmw8QB4nF+Pjs1o+zAJiRGuXRdAvhD5NSmsjwcri/HyFDsVDWj3qIX0gN6Fu9tfduvv2RoQ3VsyfuoaN3ud+eQiitl7yVGRF4yM9eXFYrBcCy/77hZfBIpFymjtWgo7GlPw8azdk4vityDtzf8XXXlDAKiOByd4KbL4cfEb4HLc+zenN8yPzJfYl4XRHQuCIbrT9v70AhWrgRNaF5FCC8r/b+PRtyfmPDZyMK/AWLAECLs35p4iusFpQyFO29ZdZUcLbd1RcvOfSuR5uUk088UBnpUWXfvIiiWdOpkzfqCxX+RZFAzj2/LiOdAggt22xV7sj5tSgVmFbJVYzoqSi/YF4y/cC0A2SuZki3p+Bt9zibodWFQsANuTxbCBpAfDzfDayiCnOAHHVDdcgAoOEMUfgMxo2QIZ2mhjCaQDwjMpZk/laAvDW1CKskun8Ey021QteKDS1jksmFw2eQ8KkjGIH1xcKIJZVxpd4qZmNVyEhvNfELQX3x2azwWzwEkYbzTk04FTEhVxV3r8J+Auog2RLoXgIdwg23OCL3vLdhv/gjr4QrnYVH1jr/9sAySE1gpLBDvFRGUzQc9m2YPvu3e5hCBRa2oXedLwo4N2oV+3BOdDjeH5YsSMMO+CPK7JP5smXOVtlJTE0=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: QWbAmAUygTiUw34roSDnmaFGUsZLI6FNWqipeaysjwNMIXSOO4l5ewJJDR3DVid83qNf93042S6oxmoA6Zg8r2NX/IzqaQhicePEIzu7nS9FanIzLI9mY4quieZqWwtaNFUTnNgMYXqRDgVpm1NSThf0NVeI2Ws4QqoD0eLhAA4/UGhlpjcdND3CSwhFNXdAV2eovjIkD7M5uUUVd4X4h+0nErUO3X0NbQMOMyP1cTonLEJuS8Pd1FdlMMxGfKIamYPjH//T5RHSnvxuIzsHOgwfvZ+qabiLtq0Cp56sWqbXqcXSbvTR8EspzB/LxvmI1zbPeK+of3hbrCCq2kMFb16BW/FXnrXpqBrTPnr6okqHZJVSZJsB+7WfR6gG5fPcA8o6uu6weWgGybfCzXXMixZJnQaY0h6nEIaghdcuHzkpz9tllmQrnWxEkOefgyjf11iO6DJWoZqxqr8l3P3UVfZhXM52mpVxKE4yGpkjl9/Ieu++tQ2/BkMj/QmwsowtBuOWsD34Cvzw6tXeGVj3AdGIQ6Zkl5qzIRQQKlCPhz4YB6DdbxFEqy6UKRqfIn7dz6D2cbUJqUEnzKGnhLldSc+/kIE3IVCKO+1dQjcgGOV28dLQualbMaGiUeusqkm4PHoRnyg4TNtMzO15yx5wLB4Kg8R7dpqhXfbrZcMvEa0=
sudo: false
